name: manage-azure-policy-1b508c73
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'

jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure new
      uses: azure/login@v1
      with:
        creds: '{"clientId":"150eb05c-da6e-4e19-9262-8dea8c812ed9","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"d6bc91f0-7f68-44ec-afd8-78acece5b3c0","tenantId":"5502fde1-90d8-49de-8f96-1821fa06eee2"}'
    - name: Deploy ARM to Azure
      uses: azure/arm-deploy@v1
      with:
        template: policies/assignPolicy/sampleARMTemplate.json
        resourceGroupName: NetworkWatcherRG
