name: manage-azure-policy-1b508c73
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'

jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure new
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1b508c73}}
    - name: Deploy ARM to Azure
      uses: azure/arm-deploy@v1
      with:
        template: policies/assignPolicy/sampleARMTemplate.json
        resourceGroupName: NetworkWatcherRG
