name: manage-azure-policy-1b508c73
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'RBAC_Policy/policies/Audit_usage_of_custom_RBAC_rules_a451c1ef-c6ca-483d-87ed-f49761e3ffb5/**'
#      - .github/workflows/manage-azure-policy-1b508c73.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1b508c73}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          RBAC_Policy/policies/Audit_usage_of_custom_RBAC_rules_a451c1ef-c6ca-483d-87ed-f49761e3ffb5/**
